generate.py, issues/style.css
=> basic 404 page

generate.py, issues/style.css
=> fixed comments inset

generate.py, issues/search.js, issues/style.css
renaming css classes to be less german, more clear or easier to copy (- -> _), also added an additional class for right aligning table columns
=> Css rename

filter_index.py, generate.py
=> I21 delayed index

generate.py, issues/style.css
=> I3 fehlerteufelchen print

issues/style.css
=> adding hyphenation and text justify to list items

generate.py, issues/style.css, validate_html.sh
closes #7 
what should the other overviews look like?
(categories, articles)
=> improved styling for the toc overview pages

issues/8405/10 Leserforum.html, issues/8405/143 Vorschau.html, issues/8405/96 Bücher.html, issues/style.css
bücher is nicer
vorschau looks like vorschau 8404
leserforum image is slightly nicer
=> various 8405 fixes

generate.py
=> changed image tag code so svg also gets an empty alt if there is none

generate.py
fewer dict strings and more properties
everything tested with:
python3 generate.py && diff -ur out out_orig 
so it really does generate the same output as before
=> wip for making generate a bit more oo

generate.py
=> pull request improvements and a bug fix for new listing sorting

generate.py
is this good enough? or should we separate it into headings with the names of the Kurse?
=> sorting Kurse by alphabet instead of separated by issues

generate.py, issues/8406/64 Die Anwendung des Monats – Lehrerkalender.html, issues/8406/69 Supervoc.html
added divs and code to parse information about additional files that are not generated prgs
=> binary downloads for articles

generate.py, issues/8404/86 Rennfahrer ohne Sturzhelm.html, issues/8406/82 Grafische Darstellung statt Zahlenfriedhof.html
=> I51 sort topics by index category

README.md, filter_index.py, filter_rss.py, generate.py, requirements.txt
using python via env so it is possible to use virtual environments 
and a requirements file to one step install python dependencies
=> python virtual environment support 

issues/8407/110 Komfortables Treiberprogramm für Centronics-Drucker.html, issues/8407/124 Croussaider – Ein Action-Spiel für den VC 20.html, issues/8407/131 Mehr über SYS.html, issues/8407/138 Autostart in Theorie und Praxis.html, issues/8407/162 Reise durch die Wunderwelt der Grafik (Teil 4).html
This PR is just meant as a quick heads-up that I started adding some of the TODOs. I'd suggest you don't merge it just yet and I'll keep updating this branch.
I have some questions, though:
- Seems you never use `<thead>`, though it has styles defined? I've used it in some places, because I thought it looked nicer. I can make these plain tables again, no problem.
- You also don't seem to use `<br/>` in tables. Are they frowned upon?
- I don't really like the look of the "Die Bedeutungen der Gerätenummern" tables in "Komfortables Treiberprogramm für Centronics-Drucker". (But the layout of the printed table is weird, too, imho). Do you have any suggestion?
=> Start adding tables

issues/8408/68 Abgerechnet wird mit dem C 64.html, issues/8408/86 ESCAPE.html
Tables for page 68 "Abgerechnet wird mit dem C 64" and page 86 "ESCAPE"
=> Some tables

Jahresinhaltsverzeichnis 1984-85.csv, issues/8504/jahresinhaltsverzeichnis.placeholderhtml, tools/csv_to_html.py
As merging the changes back into the html version started to become tedious, I wrote a tool similar to your `csv_to_header.py`, which generates the html from the csv. There are a few differences compared to the previous version because while the print version is *mostly* alphabetically sorted by title, there are a few (rare) exceptions. I still think that's acceptable; if you don't let me know and I'll fix the few affected entries manually.
Also, I only use python when I have to, so feel free to optimize :smile:.
=> Even more index fixes

issues/8410/97 Disketten-Organisation.html
=> Update 97 Disketten-Organisation.html

issues/8410/166 Mit 4 Baud über den Balkon.html
=> Update 166 Mit 4 Baud über den Balkon.html

issues/8410/82 Hardcopy MPS 801:VC 1515.html
=> Update 82 Hardcopy MPS 801:VC 1515.html

issues/8410/153 In die Geheimnisse der Floppy eingetaucht – Teil 1.html
=> Update 153 In die Geheimnisse der Floppy eingetaucht – Teil 1.html

issues/8410/157 Der gläserne VC 20 – Teil 2.html
=> Update 157 Der gläserne VC 20 – Teil 2.html

issues/8410/91 Kudiplo auch für den C 64.html
=> Update 91 Kudiplo auch für den C 64.html

issues/8410/91 POKE mal wieder.html
=> Update 91 POKE mal wieder.html

issues/8410/16 Leserforum.html
OCR fixes
Fixes in div classes
=> Update 16 Leserforum.html

issues/8411/10 Commodore Fachausstellung.html
=> Update 10 Commodore Fachausstellung.html

generate.py
=> article header line links to the TOC 

issues/8411/133 Memory Map mit Wandervorschlägen.html, issues/8411/34 David und Goliath.html, issues/8411/44 Comal – eine Einführung – Teil 1.html, issues/8411/48 Turtle-Grafik – Die schnelle Schildkröte.html, issues/8411/50 Schachmeister.html, issues/8411/8 Zuviel Programme, keine Ideen.html, issues/8411/toc.txt
- Added sub-categories as discussed in #117 
- More changes/fixes
As you didn't specify your preference regarding the bold entries in the toc, I've left then in for now, but yay or nay? 
Because I think in any case it should be consistent between issues, so if we add them now, I'll add them to the previous issues, too.
=> 8411: TOC fixes

generate.py, issues/8405/toc.txt, issues/8412/toc.txt
=> sorting articles by page number, toc category and title

generate.py, issues/8404/114 Alle Tasten, Zeichen- und Steuercodes (Teil 1).html, issues/8405/104 Alle Tasten-, Zeichen- und Steuercodes.html, issues/8405/52 Daten gut im Griff.html, issues/8406/30 Rund um die Datasette.html, issues/8406/34 Epson für Commodore 64.html, issues/8407/148 Alle Tasten-, Zeichen- und Steuercodes (Teil 3).html, issues/8407/162 Reise durch die Wunderwelt der Grafik (Teil 4).html, issues/8407/68 Lode Runner.html, issues/8408/30 Commodore 64 im neuen Kleid.html, issues/8408/34 RESET am C64.html, issues/8408/8 Piraten, Piraten.html, issues/8409/106 Fantasy-Spiele – Geschichten von Galaxien, Gnomen und Giganten.html, issues/8409/109 Schnellboot – Rettung aus der grünen Hölle.html, issues/8409/162 Datenbrennerei.html, issues/8409/42 Computer-Music – Komponieren leicht gemacht.html, issues/8409/44 Brandaktuell aus USA- Musik Neuigkeiten.html, issues/8410/20 Mehr Übersicht am Bildschirm – Test 40_80-Zeichenkarte.html, issues/8410/37 Fire-Galaxy.html, issues/8410/48 Ex-DOS – der Disketten-Doktor.html, issues/8410/8 Drucker oder Plotter.html, issues/8410/91 POKE mal wieder.html, issues/8411/10 Commodore Fachausstellung.html, issues/8411/14 MSD-Super-Disk-Drive.html, issues/8411/42 Exodus – Ultima III.html, issues/8411/43 Abenteuer selbst gemacht.html, issues/8411/8 Zuviel Programme, keine Ideen.html
that is used by google to show the article in news and stuff including a date and everything
resolves #85
=> added ld json article information

issues/8411/121 Assembler ist keine Alchimie – Teil 3.html
=> Update 121 Assembler ist keine Alchimie – Teil 3.html

issues/8411/126 Der gläserne VC 20 – Teil 3.html
=> Update 126 Der gläserne VC 20 – Teil 3.html

generate.py, issues/8404/20 Commodore Drucker unter 1000 Mark.html, issues/8404/40 Simons Basic.html, issues/8404/8 Speziell für Ihren Computer.html, issues/8405/42 Simons Basic – Teil 2.html, issues/8405/8 Datenbank für jedermann.html, issues/8406/128 Strubs – ein Precompiler für Basicprogramme (Teil 3).html, issues/8406/138 Der VC 20 als Fotolehrling.html, issues/8406/8 Hick-Hack.html, issues/8407/110 Komfortables Treiberprogramm für Centronics-Drucker.html, issues/8407/8 Steuerprobleme.html, issues/8408/114 Elektronische Aquarelle.html, issues/8408/56 Neues vom VC 20 Videochip.html, issues/8408/8 Piraten, Piraten.html, issues/8408/86 ESCAPE.html, issues/8409/137 Bücher.html, issues/8409/8 Musik lohnt sich.html, issues/8410/153 In die Geheimnisse der Floppy eingetaucht – Teil 1.html, issues/8410/67 HYPRA-LOAD- Schnelles Laden von Diskette.html, issues/8410/8 Drucker oder Plotter.html, issues/8411/117 In die Geheimnisse der Floppy eingetaucht.html, issues/8411/8 Zuviel Programme, keine Ideen.html
and a little preparation for by author pages
relates to #53 and #85
=> more fixes for author meta tags

generate.py
=> RSS sorted with the newest articles listed first

issues/8404/114 Alle Tasten, Zeichen- und Steuercodes (Teil 1).html, issues/8404/27 SX 64 im Test.html, issues/8408/151 Alle Tasten-, Zeichen- und Steuercodes – 4. Teil und Schluß.html, issues/8409/138 Assembler ist keine Alchimie.html, issues/8410/150 Assembler ist keine Alchimie – 2. Teil.html, issues/8410/86 Olympia Compact 2- ein Interface.html, issues/8411/121 Assembler ist keine Alchimie – Teil 3.html, issues/8411/13 Leserforum.html, issues/8411/161 Programmierwettbewerb- Das »intelligente« Programm.html
=> Some fixes

issues/SH8501/91 Super Line — 80 Zeichen für den C 64.html
=> SH8501 fixes

issues/8503/124 Assembler ist keine Alchimie (Teil 7).html
=> Update 124 Assembler ist keine Alchimie (Teil 7).html

issues/8503/136 Hires-3 – 15 neue Basic-Befehle (Teil 2).html
=> Update 136 Hires-3 – 15 neue Basic-Befehle (Teil 2).html

issues/8503/148 Finden mit System - Eine neuartige Suchmethode.html
=> Update 148 Finden mit System - Eine neuartige Suchmethode.html

issues/8504/36 Basic 64 — ein vielseitiger Basic-Compiler.html
=> Update 36 Basic 64 — ein vielseitiger Basic-Compiler.html

issues/8504/131 Dem Klang auf der Spur, Teil 4.html
=> Update 131 Dem Klang auf der Spur, Teil 4.html

issues/SH8502/128 So löse ich Abenteuerspiele.html
=> Update 128 So löse ich Abenteuerspiele.html

issues/SH8502/121 Mask of the Sun.html
=> Update 121 Mask of the Sun.html

issues/8506/9 Aktuell.html
=> Update 9 Aktuell.html

issues/8506/34 Big Brother druckt für Sie.html
=> Update 34 Big Brother druckt für Sie.html

issues/8506/38 Marktübersicht_ Typenraddrucker und Schreibmaschinen.html
=> Update 38 Marktübersicht_ Typenraddrucker und Schreibmaschinen.html

issues/8506/40 Der erste Kontakt mit DFÜ.html
=> Update 40 Der erste Kontakt mit DFÜ.html

issues/8506/42 Terminalprogramme.html
=> Update 42 Terminalprogramme.html

issues/8506/46 Die Netze der Post.html
=> Update 46 Die Netze der Post.html

issues/8506/151 Wir suchen die Anwendung des Monats.html
=> Update 151 Wir suchen die Anwendung des Monats.html

issues/8506/155 »Dokumentationshilfe«_ Cross-Referenz-Liste C 64.html
=> Update 155 »Dokumentationshilfe«_ Cross-Referenz-Liste C 64.html

issues/8506/54 MSE-Abtippen sicher und leicht gemacht.html
=> Update 54 MSE-Abtippen sicher und leicht gemacht.html

issues/8506/68 Kurvenplotten mit Hardcopy.html
=> Update 68 Kurvenplotten mit Hardcopy.html

issues/8506/69 HI-EDDI — Druckerroutinen.html
=> Update 69 HI-EDDI — Druckerroutinen.html

issues/8506/78 Durch POKEs zum Erfolg — Die Spiele-Trickkiste (2).html
=> Update 78 Durch POKEs zum Erfolg — Die Spiele-Trickkiste (2).html

issues/8506/80 Tips &amp; Tricks.html
=> Update 80 Tips &amp; Tricks.html

issues/8506/147 Semmelservice mit dem C 64.html
=> Update 147 Semmelservice mit dem C 64.html

issues/8506/140 Directory-Manipulationen.html
=> Update 140 Directory-Manipulationen.html

issues/8506/132 Textomat Plus kontra Vizawrite 64.html
=> Update 132 Textomat Plus kontra Vizawrite 64.html

issues/8506/130 Reset-Taster für alle Fälle.html
=> Update 130 Reset-Taster für alle Fälle.html

issues/8505/138 Assembler ist keine Alchimie — Teil 9.html
=> Update 138 Assembler ist keine Alchimie — Teil 9.html

issues/8404/119 Reise durch das Wunderland der Grafik.html
=> Update 119 Reise durch das Wunderland der Grafik.html

issues/8507/28 Marktübersicht_ Drucker.html
=> Update 28 Marktübersicht_ Drucker.html

issues/8507/27 Test_ Brother EP 44.html
=> Update 27 Test_ Brother EP 44.html

issues/8507/24 Die Alternativen.html
=> Update 24 Die Alternativen.html

issues/8507/17 Erster ausführlicher Test_ C 128, Teil 2.html
=> Update 17 Erster ausführlicher Test_ C 128, Teil 2.html

issues/8507/14 Leserforum.html
=> Update 14 Leserforum.html

issues/8507/11 Aktuell.html
=> Update 11 Aktuell.html

generate.py
Each issue has to be specified in the yymm format, so
> generate.py --issues 8410 8504
builds issues 10/84 and 4/85.
=> generate.py: add --issues option for only building selected issues

issues/SH8503/83 Dark Tower — Abenteuer im Dreistromland.html
=> Update 83 Dark Tower — Abenteuer im Dreistromland.html

issues/SH8503/52 Auf der Suche nach der 64’er.html
=> Update 52 Auf der Suche nach der 64’er.html

issues/SH8503/45 Haie und Heringe_ Fressen und gefressen werden.html
=> Update 45 Haie und Heringe_ Fressen und gefressen werden.html

issues/SH8503/21 Billard.html
=> Update 21 Billard.html

issues/SH8503/6 Checksummer 64 — Neu.html
=> Update 6 Checksummer 64 — Neu.html

issues/SH8503/142 Marktübersicht Spiele.html
=> Update 142 Marktübersicht Spiele.html

issues/SH8503/116 Shugun — Ein Brettspiel.html
=> Update 116 Shugun — Ein Brettspiel.html
